language: swift
osx_image: xcode10.2
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
notifications:
  email: false
before_install:
- env
- locale
- xcodebuild -version
- xcodebuild -showsdks
- xcodebuild -list
script:
- xcodebuild clean -project Example.xcodeproj -scheme 'DYQiniuUpload' -configuration Debug
- xcodebuild clean -project Example.xcodeproj -scheme 'DYQiniuUpload' -configuration Release
after_success:
- bash <(curl -s https://codecov.io/bash)

